name: gabslab
favicon: null
layout_spectrum: 0.24199
typography_spectrum: 0.42633037618361413
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e6eff1'
    - '#aaa7a0'
    - '#cc000d'
    - '#1c2f43'
    - '#0091a5'
  brandStrength: 0.737510607810691
  lightness: 0.2973078137729317
  saturation: 0.5624031769111753
  rhythmicContrast: 0.030978226335719228
purpose: []
