name: gabslab
favicon: null
layout_spectrum: 0.9905342105776072
typography_spectrum: 0.42633037618361413
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.737510607810691
  lightness: 0.2973078137729317
  saturation: 0.5624031769111753
  rhythmicContrast: 0.030978226335719228
purpose: []
